### ISSUE TITLE
Unable to locate element search

### ISSUE THREAD

**Issue by toannd96** [daph-td/web-scraping-Linkedin-profiles#1]
```
- Finish opening a driver ...
- Finish importing the login credentials ...
- Keying in the username ...
- Keying in the password ...
- Finish logging in ...
Traceback (most recent call last):
  File "linkedin.py", line 47, in <module>
    search = driver.find_element_by_class_name("search-global-typeahead__input always-show-placeholder") #Define id by using inspect location
  File "/home/dactoan/linkedin-scrapy/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/home/dactoan/linkedin-scrapy/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/dactoan/linkedin-scrapy/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/dactoan/linkedin-scrapy/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .search-global-typeahead__input always-show-placeholder
```

**Comment by daph-td** [comment]
Lỗi này xảy ra do trình duyệt chưa kịp load trang thì máy tính đã search element, mà trang load chưa xong thì sẽ không tìm thấy được element đó. Vậy nên để fix lỗi này thì mình sẽ thêm cú pháp "wait" để chờ trình duyệt load cho xong rồi mới bắt đầu tìm kiếm element.

**Cách 1: Explicit Waits**
Đọc thêm ở 5.1 Explicit Waits https://selenium-python.readthedocs.io/waits.html

```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Firefox(firefox_options=webdriver.FirefoxOptions())
url = 'https://www.linkedin.com/login?fromSignIn=true&trk=guest_homepage-basic_nav-header-signin'
driver.get(url)
print('- Finish opening a driver ...')

# ...
# Sau khi hoàn tất Login

wait = WebDriverWait(driver, 10)
wait.until(EC.presence_of_element_located((By.CLASS_NAME, "search-global-typeahead__input")))

# 2 - search 

#Click to search bar and input the search query
search = driver.find_element_by_class_name("search-global-typeahead__input") #Define id by using inspect location

#search_button = driver.find_element_by_id("global-nav-typeahead").click() #Click to search bar
key_word = "python"
search.send_keys(key_word)
search.send_keys(Keys.RETURN)
print('- Finish searching ...')
```

**Cách 2: Dùng sleep() function**
Trong documentation cũng có viết là "The extreme case of this is time.sleep(), which sets the condition to an exact time period to wait". Cách này thì đơn giản hơn nhưng làm giảm tính tự động của chương trình vì người viết code sẽ phải giả định một khung thời gian mà trình duyệt cần load để truyền tham số cho function, nếu trừ hao dư thời gian thì sẽ làm giảm hiệu suất chương trình

**Comment by toannd96** [comment]
Cảm ơn bạn mình đã sửa được
