### ISSUE TITLE
Not get profile user 

### ISSUE THREAD

**Issue by toannd96** [daph-td/web-scraping-Linkedin-profiles#2]
```
- Finish importing package ...
linkedin.py:18: DeprecationWarning: use options instead of firefox_options
  driver = webdriver.Firefox(firefox_options=webdriver.FirefoxOptions())
- Finish opening a driver ...
- Finish importing the login credentials ...
- Keying in the username ...
- Keying in the password ...
- Finish logging in ...
- Finish searching ...
How many pages you want to scrape: 1
linkedin.py:83: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 83 of the file linkedin.py. To get rid of this warning, pass the additional argument 'features="html5lib"' to the BeautifulSoup constructor.

  search_result = get_new_profile_ID(BeautifulSoup(driver.page_source), search_result)
Traceback (most recent call last):
  File "linkedin.py", line 95, in <module>
    profile_ID = get_new_profile_ID_for_multiple_pages()
  File "linkedin.py", line 83, in get_new_profile_ID_for_multiple_pages
    search_result = get_new_profile_ID(BeautifulSoup(driver.page_source), search_result)
  File "linkedin.py", line 68, in get_new_profile_ID
    all_links = pav.findAll('a',{'class': 'search-result__result-link ember-view'})
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by daph-td** [comment]
Theo như đọc trong phần thông báo lỗi thì để sửa lỗi này bạn thêm tham số features="html5lib" vào function BeautifulSoup ở dòng code này nhé search_result = get_new_profile_ID(BeautifulSoup(driver.page_source), search_result)
--> Code sửa thành: search_result = get_new_profile_ID(BeautifulSoup(driver.page_source, features="html5lib"), search_result)

Với cả bạn đổi cú pháp findAll thành find_all nha.

**Comment by toannd96** [comment]
Vẫn lỗi bạn ơi @daph-td 
```
How many pages you want to scrape: 1
Traceback (most recent call last):
  File "linkedin.py", line 97, in <module>
    profile_ID = get_new_profile_ID_for_multiple_pages()
  File "linkedin.py", line 85, in get_new_profile_ID_for_multiple_pages
    search_result = get_new_profile_ID(BeautifulSoup(driver.page_source, features="html5lib"), search_result)
  File "linkedin.py", line 70, in get_new_profile_ID
    all_links = pav.find_all('a',{'class': 'search-result__result-link ember-view'})
AttributeError: 'NoneType' object has no attribute 'find_all'
```
